use gagnesh;

											/*EASY-LEVEL*/
CREATE TABLE Employee2 (
    EmpID INT ,
   
);
INSERT INTO Employee2 (EmpID) 
VALUES (2), (4 ), (4), (6), (6), (7), (8), (8);

Select Max(EmpID) as [Maximum ID] from (Select EmpID from Employee2 Group by EmpID having Count(*) < 2)as Subquery;

											/*MEDIUM-LEVEL*/

CREATE TABLE Departments (
	ID INT PRIMARY KEY IDENTITY(1,1),
	DEPT_NAME varchar(MAX)
);

INSERT INTO Departments(DEPT_NAME) VALUES ('IT'), ('SALES');

CREATE TABLE Employees(
	ID INT PRIMARY KEY IDENTITY(1,1), 
	NAME varchar(MAX),
	SALARY INT,
	DEPT_ID INT
	FOREIGN KEY(DEPT_ID) REFERENCES Departments(ID)
);

INSERT INTO Employees (NAME, SALARY, DEPT_ID) 
VALUES 
('JOE', 70000, 1),
('JIM', 90000, 1),
('HENRY', 80000, 2),
('SAM', 60000, 2),
('MAX', 90000, 1);

SELECT * FROM Employees;
SELECT * FROM Departments;

SELECT D.DEPT_NAME, E.NAME, E.SALARY
FROM Departments AS D
INNER JOIN
Employees AS E
ON D.ID = E.DEPT_ID
WHERE E.SALARY IN 
(
	SELECT MAX(E2.SALARY)
	FROM Employees AS E2
	WHERE E2.DEPT_ID = E.DEPT_ID
)
											/*HARD-LEVEL*/

CREATE TABLE A (EMPID INT PRIMARY KEY, ENAME VARCHAR(MAX), SALARY INT)

INSERT INTO A (EMPID, ENAME, SALARY) VALUES (1, 'AA', 1000), (2, 'BB', 300)

CREATE TABLE B (EMPID INT PRIMARY KEY, ENAME VARCHAR(MAX), SALARY INT)

INSERT INTO B (EMPID, ENAME, SALARY) VALUES (2, 'BB', 400), (3, 'CC', 100);

SELECT EMPID, MIN(ENAME) AS ENAME, MIN(SALARY) AS SALARY
FROM
(
	SELECT * FROM A
	UNION ALL
	SELECT * FROM B
) AS INTERMEDIATE_RESULT
GROUP BY EMPID